/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import HoverButtons.Controller;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import EstilosComponents.GestionEncabezadoTabla;
import controller.ControllerProyectos;
import java.util.List;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import layouts.RecuperarTarea;
/**
 *
 * @author HP
 */
public class TareasEliminadas extends javax.swing.JFrame {
    public Controller controller;
    public TareasPendientesPorRealizar tareasPersonales;
    private ControllerProyectos conexion = new ControllerProyectos(); 
    private int id_user;
    /**
     * Creates new form TareasEliminadas
     */
    DefaultTableModel modelo;
    public TareasEliminadas() {
        initComponents();
        this.setLocationRelativeTo(null);
        controller = new Controller(this);
    }
    
    public void obtenerVentanAnterior(TareasPendientesPorRealizar v1){
      this.tareasPersonales = v1;
    }
    public void set_id_user(int id){
        this.id_user = id;
        this.agregar_datos_tabla();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        recuperar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        icono_Regresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(19, 30, 35));
        jPanel2.setMaximumSize(new java.awt.Dimension(1333, 666));
        jPanel2.setMinimumSize(new java.awt.Dimension(1333, 666));
        jPanel2.setPreferredSize(new java.awt.Dimension(1333, 666));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new java.awt.BorderLayout());

        recuperar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        recuperar.setText("RECUPERAR TAREAS");
        recuperar.setContentAreaFilled(false);
        recuperar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recuperar.setFocusPainted(false);
        recuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarActionPerformed(evt);
            }
        });
        jPanel3.add(recuperar, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(64, 97, 226, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAREAS ELIMINADAS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(64, 66, 187, 25);

        tabla_datos.setBackground(new java.awt.Color(19, 30, 35));
        tabla_datos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabla_datos.setForeground(new java.awt.Color(255, 255, 255));
        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_datos.setColumnSelectionAllowed(true);
        tabla_datos.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(tabla_datos);
        tabla_datos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(60, 159, 1214, 465);

        icono_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        icono_Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icono_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icono_RegresarMouseClicked(evt);
            }
        });
        jPanel2.add(icono_Regresar);
        icono_Regresar.setBounds(30, 0, 60, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarActionPerformed
        System.out.println("recuperar una tarea");
        RecuperarTarea recuperar = new RecuperarTarea(this,true); 
        recuperar.set_id_user(this.id_user);
        recuperar.setVisible(true);
        this.agregar_datos_tabla();
    }//GEN-LAST:event_recuperarActionPerformed

    private void icono_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icono_RegresarMouseClicked
      this.tareasPersonales.agregar_datos_tabla();
      this.tareasPersonales.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_icono_RegresarMouseClicked
    public void agregar_datos_tabla(){
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int colum){
                return false;
            }
        };
        
        TableRowSorter<TableModel> OrdenarTabla = new TableRowSorter<TableModel>(modelo); 
        
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE DE LA TAREA");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRIORIDAD");
        modelo.addColumn("FECHA LIMITE");
        
        List<String[]> datos = this.conexion.tareas_eliminadas(this.id_user);
        for(String[] dato : datos){
            modelo.addRow(dato);
        }
        this.tabla_datos.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareasEliminadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareasEliminadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareasEliminadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareasEliminadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareasEliminadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icono_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton recuperar;
    private javax.swing.JTable tabla_datos;
    // End of variables declaration//GEN-END:variables
}
