/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import layouts.ModificarTareaPersonal;
import layouts.AgregarNuevaTareaPersonal;
import layouts.EliminarTarea;



import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import EstilosComponents.GestionEncabezadoTabla;
import controller.ControllerProyectos;
import controller.controllerUsuario;
import HoverButtons.ControllerGestionarTareas;

import java.util.List;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


public class TareasPendientesPorRealizar extends javax.swing.JFrame {
    
    public ControllerGestionarTareas ControllerGestionarTareas;
    private controllerUsuario datos_user;
    private ControllerProyectos conexion = new ControllerProyectos();
    private TareasEliminadas tareasEliminadas;
    
    
    DefaultTableModel modelo;
    private PrincipalesOpciones Menu;
    
    public TareasPendientesPorRealizar() {
        initComponents();
        tareasEliminadas = new TareasEliminadas();
        Menu = new PrincipalesOpciones();
        
        
        this.setLocationRelativeTo(null);
        ControllerGestionarTareas = new ControllerGestionarTareas(this); 
    //this.table_tareas.setBackground(Color.HSBtoRGB(225,225,225));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_tabla = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos_principal1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ModificarTarea = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BtnAgregarNuevaTarea = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BtnEliminarTarea = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        BtnLimpiarListaTareas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ComboFiltrar = new javax.swing.JComboBox<>();
        papelera = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenuItem1.setText("opcion1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_tabla.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        menu_tabla.add(jMenuItem2);

        jMenu1.setText("jMenu1");
        menu_tabla.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(19, 30, 35));
        jPanel2.setMinimumSize(new java.awt.Dimension(1333, 666));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1333, 666));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAREAS PENDIENTES POR REALIZAR");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(106, 78, 320, 25);

        tabla_datos_principal1.setBackground(new java.awt.Color(19, 30, 35));
        tabla_datos_principal1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabla_datos_principal1.setForeground(new java.awt.Color(255, 255, 255));
        tabla_datos_principal1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_datos_principal1.setColumnSelectionAllowed(true);
        tabla_datos_principal1.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(tabla_datos_principal1);
        tabla_datos_principal1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(100, 211, 1132, 369);

        jPanel4.setLayout(new java.awt.BorderLayout());

        ModificarTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModificarTarea.setText("Modificar Tarea");
        ModificarTarea.setContentAreaFilled(false);
        ModificarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarTarea.setFocusPainted(false);
        ModificarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarTareaActionPerformed(evt);
            }
        });
        jPanel4.add(ModificarTarea, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(106, 126, 188, 39);

        jPanel5.setLayout(new java.awt.BorderLayout());

        BtnAgregarNuevaTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregarNuevaTarea.setText("Agregar Nueva Tarea");
        BtnAgregarNuevaTarea.setContentAreaFilled(false);
        BtnAgregarNuevaTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregarNuevaTarea.setFocusPainted(false);
        BtnAgregarNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarNuevaTareaActionPerformed(evt);
            }
        });
        jPanel5.add(BtnAgregarNuevaTarea, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(419, 126, 181, 39);

        jPanel6.setLayout(new java.awt.BorderLayout());

        BtnEliminarTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEliminarTarea.setText("Eliminar Tarea");
        BtnEliminarTarea.setContentAreaFilled(false);
        BtnEliminarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminarTarea.setFocusPainted(false);
        BtnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarTareaActionPerformed(evt);
            }
        });
        jPanel6.add(BtnEliminarTarea, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(719, 126, 171, 39);

        jPanel7.setLayout(new java.awt.BorderLayout());

        BtnLimpiarListaTareas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLimpiarListaTareas.setText("Limpiar Lista de Tareas");
        BtnLimpiarListaTareas.setContentAreaFilled(false);
        BtnLimpiarListaTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiarListaTareas.setFocusPainted(false);
        BtnLimpiarListaTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarListaTareasActionPerformed(evt);
            }
        });
        jPanel7.add(BtnLimpiarListaTareas, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(998, 123, 201, 39);

        jPanel3.setLayout(new java.awt.BorderLayout());

        ComboFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComboFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FILTRAR", "FECHA LIMITE", "PRIORIDAD", "RECIENTES" }));
        ComboFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(ComboFiltrar, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(1243, 123, 109, 33);

        papelera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        papelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image (2).png"))); // NOI18N
        papelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        papelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                papeleraMouseClicked(evt);
            }
        });
        jPanel2.add(papelera);
        papelera.setBounds(1250, 580, 90, 88);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 0, 60, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1362, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setv1(PrincipalesOpciones v11){
      this.Menu = v11;
    }
    
    public void agregar_datos_tabla(){
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int colum){
                return false;
            }
        };
        
        TableRowSorter<TableModel> OrdenarTabla = new TableRowSorter<TableModel>(modelo); 
        
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE DE LA TAREA");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRIORIDAD");
        modelo.addColumn("FECHA LIMITE");
        
        List<String[]> datos = this.conexion.tareas_usuario(this.datos_user.getId_usuario());
        for(String[] dato : datos){
            modelo.addRow(dato);
        }
        this.tabla_datos_principal1.setModel(modelo);
    }
    public void set_usuario_date(controllerUsuario user){
        this.datos_user = user;
        this.agregar_datos_tabla();
    }
    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void BtnAgregarNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarNuevaTareaActionPerformed

        AgregarNuevaTareaPersonal agregarTarea = new AgregarNuevaTareaPersonal(this, true);
        agregarTarea.valor_insert(this.datos_user.getId_usuario());
        agregarTarea.setVisible(true);
        this.agregar_datos_tabla();
    }//GEN-LAST:event_BtnAgregarNuevaTareaActionPerformed

    private void BtnLimpiarListaTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarListaTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarListaTareasActionPerformed

    private void ModificarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarTareaActionPerformed
        // TODO add your handling code here:
        
        ModificarTareaPersonal modificarTarea = new ModificarTareaPersonal( (java.awt.Frame) this.getParent(), true);
        modificarTarea.dar_valores_predeterminado(this.datos_user.getId_usuario());
        modificarTarea.setVisible(true);
        this.agregar_datos_tabla();
    }//GEN-LAST:event_ModificarTareaActionPerformed

    private void BtnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarTareaActionPerformed
        // TODO add your handling code here:
        EliminarTarea eliminarTarea = new EliminarTarea(this, true);
        eliminarTarea.setVisible(true);
    }//GEN-LAST:event_BtnEliminarTareaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        this.Menu.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void papeleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papeleraMouseClicked
        // TODO add your handling code here:
        
        this.tareasEliminadas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_papeleraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareasPendientesPorRealizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAgregarNuevaTarea;
    public javax.swing.JButton BtnEliminarTarea;
    public javax.swing.JButton BtnLimpiarListaTareas;
    public javax.swing.JComboBox<String> ComboFiltrar;
    public javax.swing.JButton ModificarTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu menu_tabla;
    private javax.swing.JLabel papelera;
    private javax.swing.JTable tabla_datos_principal1;
    // End of variables declaration//GEN-END:variables
}
