/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import layouts.ModificarTareaPersonal;
import layouts.AgregarNuevaTareaPersonal;
import layouts.EliminarTarea;



import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import EstilosComponents.GestionEncabezadoTabla;
import controller.ControllerProyectos;
import controller.controllerUsuario;
import java.util.List;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
public class TareasPendientesPorRealizar extends javax.swing.JFrame {
    public ControllerGestionarTareas ControllerGestionarTareas;
    private controllerUsuario datos_user;
    private ControllerProyectos conexion = new ControllerProyectos();
    DefaultTableModel modelo;
    public TareasPendientesPorRealizar() {
        initComponents();
        this.setLocationRelativeTo(null);
        ControllerGestionarTareas = new ControllerGestionarTareas(this);        

    //this.table_tareas.setBackground(Color.HSBtoRGB(225,225,225));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos_principal1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ModificarTarea = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BtnAgregarNuevaTarea = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BtnEliminarTarea = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        BtnLimpiarListaTareas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ComboFiltrar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(19, 30, 35));
        jPanel2.setMinimumSize(new java.awt.Dimension(1333, 666));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1333, 666));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        regresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regresar.setText("REGRESAR");
        regresar.setContentAreaFilled(false);
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.setFocusPainted(false);
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 106, 0, 0);
        jPanel2.add(jPanel1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAREAS PENDIENTES POR REALIZAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 106, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        tabla_datos_principal1.setBackground(new java.awt.Color(19, 30, 35));
        tabla_datos_principal1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabla_datos_principal1.setForeground(new java.awt.Color(255, 255, 255));
        tabla_datos_principal1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_datos_principal1.setColumnSelectionAllowed(true);
        tabla_datos_principal1.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(tabla_datos_principal1);
        tabla_datos_principal1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1116;
        gridBagConstraints.ipady = 350;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(46, 100, 0, 0);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jPanel4.setLayout(new java.awt.BorderLayout());

        ModificarTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModificarTarea.setText("Modificar Tarea");
        ModificarTarea.setContentAreaFilled(false);
        ModificarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarTarea.setFocusPainted(false);
        ModificarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarTareaActionPerformed(evt);
            }
        });
        jPanel4.add(ModificarTarea, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 106, 0, 0);
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.BorderLayout());

        BtnAgregarNuevaTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregarNuevaTarea.setText("Agregar Nueva Tarea");
        BtnAgregarNuevaTarea.setContentAreaFilled(false);
        BtnAgregarNuevaTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregarNuevaTarea.setFocusPainted(false);
        BtnAgregarNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarNuevaTareaActionPerformed(evt);
            }
        });
        jPanel5.add(BtnAgregarNuevaTarea, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 125, 0, 0);
        jPanel2.add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.BorderLayout());

        BtnEliminarTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEliminarTarea.setText("Eliminar Tarea");
        BtnEliminarTarea.setContentAreaFilled(false);
        BtnEliminarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminarTarea.setFocusPainted(false);
        BtnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarTareaActionPerformed(evt);
            }
        });
        jPanel6.add(BtnEliminarTarea, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 119, 0, 0);
        jPanel2.add(jPanel6, gridBagConstraints);

        jPanel7.setLayout(new java.awt.BorderLayout());

        BtnLimpiarListaTareas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLimpiarListaTareas.setText("Limpiar Lista de Tareas");
        BtnLimpiarListaTareas.setContentAreaFilled(false);
        BtnLimpiarListaTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiarListaTareas.setFocusPainted(false);
        BtnLimpiarListaTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarListaTareasActionPerformed(evt);
            }
        });
        jPanel7.add(BtnLimpiarListaTareas, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 108, 0, 0);
        jPanel2.add(jPanel7, gridBagConstraints);

        jPanel3.setLayout(new java.awt.BorderLayout());

        ComboFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComboFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FILTRAR", "FECHA LIMITE", "PRIORIDAD", "RECIENTES" }));
        ComboFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(ComboFiltrar, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -30;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 11, 0, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image (2).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 40, 14, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1362, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void agregar_datos_tabla(){
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int colum){
                return false;
            }
        };
        
        TableRowSorter<TableModel> OrdenarTabla = new TableRowSorter<TableModel>(modelo); 
        
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE DE LA TAREA");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRIORIDAD");
        modelo.addColumn("FECHA LIMITE");
        
        List<String[]> datos = this.conexion.tareas_usuario(this.datos_user.getId_usuario());
        for(String[] dato : datos){
            modelo.addRow(dato);
        }
        this.tabla_datos_principal1.setModel(modelo);
    }
    public void set_usuario_date(controllerUsuario user){
        this.datos_user = user;
        this.agregar_datos_tabla();
    }
    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void BtnAgregarNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarNuevaTareaActionPerformed
        // TODO add your handling code here:
        
        AgregarNuevaTareaPersonal agregarTarea = new AgregarNuevaTareaPersonal(this, true);
        agregarTarea.setVisible(true);
        
    }//GEN-LAST:event_BtnAgregarNuevaTareaActionPerformed

    private void BtnLimpiarListaTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarListaTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarListaTareasActionPerformed

    private void ModificarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarTareaActionPerformed
        // TODO add your handling code here:
        
        ModificarTareaPersonal modificarTarea = new ModificarTareaPersonal( (java.awt.Frame) this.getParent(), true);
        modificarTarea.setVisible(true);
    }//GEN-LAST:event_ModificarTareaActionPerformed

    private void BtnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarTareaActionPerformed
        // TODO add your handling code here:
        EliminarTarea eliminarTarea = new EliminarTarea(this, true);
        eliminarTarea.setVisible(true);
    }//GEN-LAST:event_BtnEliminarTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareasPendientesPorRealizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareasPendientesPorRealizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnAgregarNuevaTarea;
    public javax.swing.JButton BtnEliminarTarea;
    public javax.swing.JButton BtnLimpiarListaTareas;
    public javax.swing.JComboBox<String> ComboFiltrar;
    public javax.swing.JButton ModificarTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton regresar;
    private javax.swing.JTable tabla_datos_principal1;
    // End of variables declaration//GEN-END:variables
}
