/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import EstilosComponents.GestionEncabezadoTabla;
import controller.ControllerProyectos;
import estilosComponents.CentrarDatosDeTabla;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;



/**
 *
 * @author Usuario
 */
public class TareasComoParticipante extends javax.swing.JFrame {

    private AdministrarProyectos MenuProyectos;
    private ControllerProyectos conexion = new ControllerProyectos();
    private int id_proyecto = -1;
    private int id_usuario = 1;
  /**
   * Creates new form GestionarTareaComoAdministrador
   */
  DefaultTableModel modelo;
  
  
  public TareasComoParticipante() {
    initComponents();
    
    modelo = new DefaultTableModel();
  }
  public void iniciar_componentes (AdministrarProyectos  datos,int id_proyecto,int id_user){
    this.MenuProyectos = datos;
    this.id_proyecto = id_proyecto;
    this.id_usuario = id_user;
    this.completar_datos_archivo();
    this.cambiar_datos();
  }
  
  public void completar_datos_archivo(){
      DefaultTableModel modelo = new DefaultTableModel(){
          @Override
          public boolean isCellEditable(int row,int colum){
              return false;
          }
      };
      modelo.addColumn("ESTADO");
      modelo.addColumn("id");
      modelo.addColumn("Nombre de la tarea");
      modelo.addColumn("DESCRIPCION");
      modelo.addColumn("PRIORIDAD");
      modelo.addColumn("FECHA LIMITE");

    List<String[]> datos = this.conexion.mostras_tareas_usuarios(id_usuario, id_proyecto);
      
    for(String[] dato : datos){
        //modelo.addRow(dato);
        Object[] fila = new Object[dato.length + 1];
        fila[0] = (dato[8].equals("hecho"))? true:false; // Inicializa la casilla de verificación como desmarcada
        System.arraycopy(dato, 0, fila, 1, dato.length);
        modelo.addRow(fila);
    }

    this.datos_usuario.setModel(modelo);
  
  }
  public void cambiar_datos(){
      String[] datos = this.conexion.datos_proyecto(this.id_proyecto);
      this.label_nombre_proyecto.setText(datos[1]);
      this.label_descripcion.setText(datos[2]);
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_tareas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos_usuario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        label_descripcion = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        icono_Regresar = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JToggleButton();
        label_nombre_proyecto = new javax.swing.JLabel();

        table_tareas.setBackground(new java.awt.Color(19, 30, 35));
        table_tareas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        table_tareas.setForeground(new java.awt.Color(255, 255, 255));
        table_tareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_tareas.setInheritsPopupMenu(true);
        table_tareas.setName(""); // NOI18N
        table_tareas.setRowHeight(50);
        table_tareas.setRowMargin(1);
        jScrollPane2.setViewportView(table_tareas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 30, 35));
        jPanel1.setMaximumSize(new java.awt.Dimension(1333, 666));
        jPanel1.setPreferredSize(new java.awt.Dimension(1333, 666));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(19, 30, 35));

        datos_usuario.setBackground(new java.awt.Color(19, 30, 35));
        datos_usuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        datos_usuario.setForeground(new java.awt.Color(255, 255, 255));
        datos_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datos_usuario.setColumnSelectionAllowed(true);
        datos_usuario.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(datos_usuario);

        label_descripcion.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_descripcion)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(46, 121, 1279, 495);

        jButton2.setBackground(new java.awt.Color(0, 140, 219));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GUARDAR CAMBIOS");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1030, 620, 263, 41);

        icono_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        icono_Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icono_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icono_RegresarMouseClicked(evt);
            }
        });
        jPanel1.add(icono_Regresar);
        icono_Regresar.setBounds(50, 40, 60, 60);

        btn_actualizar.setText("ACTUALIZAR ");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_actualizar);
        btn_actualizar.setBounds(870, 50, 190, 60);

        label_nombre_proyecto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_nombre_proyecto.setForeground(new java.awt.Color(255, 255, 255));
        label_nombre_proyecto.setText("NOMBRE DEL PROYECTO");
        jPanel1.add(label_nombre_proyecto);
        label_nombre_proyecto.setBounds(60, 100, 215, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void icono_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icono_RegresarMouseClicked
        // TODO add your handling code here:

        this.MenuProyectos.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_icono_RegresarMouseClicked

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        
    }//GEN-LAST:event_btn_actualizarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TareasComoParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TareasComoParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TareasComoParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TareasComoParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TareasComoParticipante().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_actualizar;
    private javax.swing.JTable datos_usuario;
    private javax.swing.JLabel icono_Regresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_descripcion;
    private javax.swing.JLabel label_nombre_proyecto;
    private javax.swing.JTable table_tareas;
    // End of variables declaration//GEN-END:variables
}
