/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import EstilosComponents.GestionEncabezadoTabla;
import estilosComponents.CentrarDatosDeTabla;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import layouts.EliminarIntegrante;
import layouts.EliminarTarea;



/**
 *
 * @author Usuario
 */
public class VisualizarIntegrantes extends javax.swing.JFrame {
    
    private GestionarTareaComoAdministrador MenuAdministrador;
    private EliminarIntegrante eliminarintegrante;
    private List<String[]> listaIntegrantes;
  /**
   * Creates new form GestionarTareaComoAdministrador
   */
  DefaultTableModel modelo;
  
  public VisualizarIntegrantes() {
      
    initComponents();
    
    modelo = new DefaultTableModel();
  }
  
  public void refrescarListaIntegrantes(){
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row,int colum){
            return false;
        }
    };

    modelo.addColumn("ID");
    modelo.addColumn("NOMBRE DEL INTEGRANTE");
    modelo.addColumn("EMAIL");

    List<String[]> datos = this.obtenerListaIntegrantes();
    for(String[] dato : datos){
        modelo.addRow(dato);
    }

    this.tabla_integrantesDelProyecto.setModel(modelo);
  }
  
  public void obtenerVentanAnterior(GestionarTareaComoAdministrador v1){
    MenuAdministrador = v1;
  }
  
  public List<String[]> obtenerListaIntegrantes(){
    return this.MenuAdministrador.controllerGTCA.obtenerTodosLosIntegrantes(MenuAdministrador.id_proyecto);
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_integrantesDelProyecto = new javax.swing.JTable();
        icono_Regresar = new javax.swing.JLabel();
        panelRound3 = new Clases.PanelRound();
        Btn_EliminarIntegrantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 30, 35));
        jPanel1.setMaximumSize(new java.awt.Dimension(1333, 666));
        jPanel1.setMinimumSize(new java.awt.Dimension(1333, 666));
        jPanel1.setPreferredSize(new java.awt.Dimension(1333, 666));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(19, 30, 35));

        tabla_integrantesDelProyecto.setBackground(new java.awt.Color(19, 30, 35));
        tabla_integrantesDelProyecto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabla_integrantesDelProyecto.setForeground(new java.awt.Color(255, 255, 255));
        tabla_integrantesDelProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_integrantesDelProyecto.setColumnSelectionAllowed(true);
        tabla_integrantesDelProyecto.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(tabla_integrantesDelProyecto);
        tabla_integrantesDelProyecto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 1220;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 103, 23);
        jPanel1.add(jPanel2, gridBagConstraints);

        icono_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        icono_Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icono_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icono_RegresarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        jPanel1.add(icono_Regresar, gridBagConstraints);

        panelRound3.setBackground(new java.awt.Color(8, 131, 20));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);
        panelRound3.setLayout(new java.awt.BorderLayout());

        Btn_EliminarIntegrantes.setBackground(new java.awt.Color(8, 131, 20));
        Btn_EliminarIntegrantes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Btn_EliminarIntegrantes.setForeground(new java.awt.Color(255, 255, 255));
        Btn_EliminarIntegrantes.setText("ELIMINAR INTEGRANTES");
        Btn_EliminarIntegrantes.setBorder(null);
        Btn_EliminarIntegrantes.setContentAreaFilled(false);
        Btn_EliminarIntegrantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_EliminarIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarIntegrantesActionPerformed(evt);
            }
        });
        panelRound3.add(Btn_EliminarIntegrantes, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 950, 0, 0);
        jPanel1.add(panelRound3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void Btn_EliminarIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarIntegrantesActionPerformed
        eliminarintegrante = new EliminarIntegrante(this, true);
        eliminarintegrante.obtenerVentanaAnteior(MenuAdministrador);
        eliminarintegrante.obtenerVisualizarIntegrantes(this);
        eliminarintegrante.setVisible(true);
  }//GEN-LAST:event_Btn_EliminarIntegrantesActionPerformed

    private void icono_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icono_RegresarMouseClicked
        this.MenuAdministrador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_icono_RegresarMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VisualizarIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VisualizarIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VisualizarIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VisualizarIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VisualizarIntegrantes().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_EliminarIntegrantes;
    private javax.swing.JLabel icono_Regresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private Clases.PanelRound panelRound3;
    private javax.swing.JTable tabla_integrantesDelProyecto;
    // End of variables declaration//GEN-END:variables
}
