/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package layouts;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Usuario
 */
public class CalendarioAsignarNuevaTarea extends javax.swing.JDialog {
  private AsignarNuevaTarea ventanaAnterior;
  private String fechaSeleccionada;
  /**
   * Creates new form CalendarioAsignarNuevaTarea
   */
  public CalendarioAsignarNuevaTarea(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }
  
  public String getFechaSeleccionada(){
    Date fechaCalendario = calendario.getDate();
    if (fechaCalendario != null) {
      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      this.fechaSeleccionada = dateFormat.format(fechaCalendario); 
    } else {
      this.fechaSeleccionada = "0000/00/00";
    } 
    
    System.out.println("LA FECHA SELECCIONADA ES: "+this.fechaSeleccionada);
    
    return this.fechaSeleccionada;
  }
  
  
  public com.toedter.calendar.JCalendar obtenerCalendario(){
    return this.calendario;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    calendario = new com.toedter.calendar.JCalendar();
    boton_guardar_fecha = new javax.swing.JToggleButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    boton_guardar_fecha.setText("ACEPTAR");
    boton_guardar_fecha.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton_guardar_fechaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(boton_guardar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(171, 171, 171))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(boton_guardar_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        .addGap(14, 14, 14))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  public void obtenerVentanaAnterior(AsignarNuevaTarea ventanaAnterior){
    this.ventanaAnterior = ventanaAnterior;
  }
  
  private void boton_guardar_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_fechaActionPerformed
    //evento boton
    this.ventanaAnterior.getBtnCalendario().setText(this.getFechaSeleccionada());
    this.dispose();
  }//GEN-LAST:event_boton_guardar_fechaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CalendarioAsignarNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CalendarioAsignarNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CalendarioAsignarNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CalendarioAsignarNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        CalendarioAsignarNuevaTarea dialog = new CalendarioAsignarNuevaTarea(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton boton_guardar_fecha;
  private com.toedter.calendar.JCalendar calendario;
  // End of variables declaration//GEN-END:variables
}
